#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'


# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Erros foram encontrados no PHPStan. Corrija antes de continuar... 👮🏽";
    exit 1;
fi;

# rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa! os testes encontraram erros. Corrija antes de continuar... 👮🏽";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;


echo -e "${BRed} Tudo certo! Commit autorizado 👮🏽🎉 ${NC}";
exit 0;
